apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ .Values.clusterName }}-md-0
spec:
  template:
    spec:
      imageName: ubuntu-22.04
      placementGroupName: md-0
      type: {{ .Values.HCLOUD_WORKER_MACHINE_TYPE }}
