apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ .Values.clusterName }}-control-plane
spec:
  template:
    spec:
      imageName: ubuntu-22.04
      placementGroupName: control-plane
      type: {{ .Values.HCLOUD_CONTROL_PLANE_MACHINE_TYPE }}
