apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: {{ .Values.clusterName }}-md-0
  name: {{ .Values.clusterName }}-md-0
spec:
  clusterName: {{ .Values.clusterName }}
  replicas: {{ .Values.WORKER_MACHINE_COUNT }}
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        nodepool: {{ .Values.clusterName }}-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.clusterName }}-md-0
      clusterName: {{ .Values.clusterName }}
      failureDomain: {{ .Values.HCLOUD_REGION }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ .Values.clusterName }}-md-0
      version: {{ .Values.KUBERNETES_VERSION }}
